### ISSUE TITLE
Simpler form

### ISSUE THREAD

**Issue by absolux** [keithamus/proposal-array-last#22]
What about simply use `-1` as index

```js
let arr = ['foo', 'bar', 'baz']

console.log(arr[-1]) // prints "baz"
```

**Comment by keithamus** [comment]
I'm afraid this wouldn't be possible due to that have existing behaviour today, which people - unfortunately - rely on. Right now code that uses that would return `undefined` and for that to change to a value would have a large potential to break the web.
