### ISSUE TITLE
Transfer repo to tc39 org

### ISSUE THREAD

**Issue by chicoxyzzy** [keithamus/proposal-array-last#30]
This proposal is stage 1 so it should move under TC39 org

**Comment by ljharb** [comment]
Instructions here: https://github.com/tc39/proposals#onboarding-existing-proposals

**Comment by keithamus** [comment]
I am not an admin of `tc39-transfer`. @ljharb according to the docs I should contact you.

**Comment by ljharb** [comment]
lol whoops, invite sent https://github.com/tc39-transfer

**Comment by keithamus** [comment]
It's been transferred!
