### ISSUE TITLE
Last as a getter/setter

### ISSUE THREAD

**Issue by jridgewell** [keithamus/proposal-array-last#4]
Instead of defining a getter/setter at `-1` (very scary) or `:-1` (which we don’t have precedent for), why not define `last` as a one?

**Comment by ljharb** [comment]
I suspect that would have significant web compat risk; most of the speculative polyfills define `last` as a function, not a getter.

**Comment by keithamus** [comment]
Personally I'm not especially fond of `last` as a getter, regardless of the web-compat issues. [A last getter was floated a while ago (tc39/ecma262#36)](https://github.com/tc39/ecma262/pull/36) and stalled for web-compat issues.

**Comment by keithamus** [comment]
Closing this. The Readme has been updated to reflect the current state of this proposal which features `Array.prototype.end` getter/setter.
