### ISSUE TITLE
Polyfill does not use semi-colons

### ISSUE THREAD

**Issue by JakeChampion** [keithamus/proposal-array-last#8]
I would have expected the polyfill to make use of semi-colons because the TC39 recommend the use of semi-colons.

**Comment by ljharb** [comment]
That recommendation is not yet merged.

(Separately, polyfills included in proposal repos are not intended for production use, and are solely intended to be explanatory - as such, it’s not really important that the code be robust)

**Comment by keithamus** [comment]
In reality the polyfill is overkill anyway, you probably just want:

```js
Object.defineProperty(Array.prototype, 'end', {
  get() {
    return this[this.length-1];
  },
  set(value) {
    return this[this.length ? this.length-1 : 0] = value;
  }
});
```
